openapi: 3.0.1
info:
  title: Personal Sensor Data Plugin
  description: A plugin that allows the user to get air quality and temperature and humidity readings from a set of sensors located inside his house. Sends back the last 1h of data.
  version: 'v1'
paths:
  /sensors/airgradient:d03276:
    get:
      operationId: getSensorData
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    wifi:
                      type: number
                      description: wifi signal strength for the sensor box
                    rco2:
                      type: number
                      description: CO2 levels in ppm
                    pm02:
                      type: number
                      description: PM 2.5 in μg/m³
                    tvoc_index:
                      type: number
                      description: volatile organic compound index, 100 is normal, scale goes from 0 to 500
                    nox_index:
                      type: number
                      description: nitric oxides index, 1 is normal, scale goes from 0 to 500
                    atmp:
                      type: number
                      description: temperature in degree celsius
                    rhum:
                      type: number
                      description: relative humidity in percent
                    pressure:
                      type: number
                      description: barometric pressure in hPa
                    ts:
                      type: string
                      description: unix timestamp of the measure (UTC time)
                  required: [ "wifi", "rco2", "pm02", "tvoc_index", "nox_index", "atmp", "rhum", "pressure", "ts" ]
                  description: The sensor data sampled at a 30 seconds interval
