name = "airgradient"
compatibility_date = "2023-07-22"
main = "./dist/index.min.mjs"
account_id = "cd9e33fd195d65e911ed2dc87f1cf4c6"
no_bundle = true

[vars]
ACCOUNT_ID = "cd9e33fd195d65e911ed2dc87f1cf4c6"
APP_VERSION = "1.0.0"

[[analytics_engine_datasets]]
binding = "MEASURES"
